server:
  port: 8080
  servlet:
    context-path: /api/v1
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/databaze
      username: uzivatel
      password: hodgeslo
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
